add stats tab
geoprotech/PowerEye_2 pull request #14
Opened 2024-04-04 11:15 UTC by artiebears13

Works!!!

2024-04-06 09:47 UTC, TeeMan508 requested changes

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/labels/label_blue_text.py
> +class LabelBlueText(BaseLabel):
Аналогично нижнему.

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/tab_header/tab_header_name_layout.py
> +        | logo_img | logo_text |
Точно отсюда докстринг?

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/line_edit/value_line_edit.py
> +        super().focusOutEvent(event)
И еще DimensionlessNumericLineEdit, для безразмерных величин

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/dimensional_stats_label.py
> +    def mouseMoveEvent(self, e: QEvent) -> None:  # noqa
![image](https://github.com/geoprotech/PowerEye_2/assets/57092435/93efd3cb-9a17-475e-9be9-b78179a115f9)

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/drag_target_indicator.py
> +class DragTargetIndicator(QLabel):
-> DragTarget...

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/drag_target_indicator.py
> +    A QLabel subclass representing a drop target indicator during drag and drop operations.
-> ...a drop target...

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/drag_target_indicator.py
> +        __init__(parent=None): Constructor method. Initializes the drag target indicator.
-> ...the drag target...

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/drag_widget.py
> +    def dragEnterEvent(self, e: QEvent) -> None:  # noqa
![image](https://github.com/geoprotech/PowerEye_2/assets/57092435/ea759d99-d58d-48b5-a9af-593e1f4bf900)

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/stats_list_widget.py
> +class StatsListWidget(QWidget):
DraggableStatsWdget

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/stats_list_widget.py
> +    def make(self) -> None:
Думаю можно это все в pre_setup поместить, а Make пустым оставить. Мб где-нибудь еще определим подобный виджет

2024-04-06 09:47 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/dimensional_stats_label.py
> +        self.shadow.setColor(QColor(40, 191, 201, 50))
Стоит из стилей брать цвет

2024-04-08 07:29 UTC, artiebears13 commented on bin/gui/widgets/labels/label_white_text.py
> +class LabelWhiteText(BaseLabel):
нет

2024-04-08 07:29 UTC, artiebears13 commented on bin/gui/widgets/labels/label_blue_text.py
> +class LabelBlueText(BaseLabel):
аналогично нет

2024-04-08 07:29 UTC, artiebears13 commented on bin/gui/widgets/layouts/tab_header/tab_header_name_layout.py
> +        | logo_img | logo_text |
нет)

2024-04-08 07:31 UTC, artiebears13 commented on bin/gui/widgets/layouts/tab_header/tab_header_layout.py
> +    def __init__(self, parent: QWidget, buttons_layout: HorizontalLayout):
хзхз

2024-04-08 07:32 UTC, artiebears13 commented on bin/gui/widgets/line_edit/value_line_edit.py
> +        super().focusOutEvent(event)
и то верно

2024-04-08 11:16 UTC, artiebears13 commented on bin/gui/widgets/buttons/text_icon_button.py
> +class TextIconButton(BaseButton):
сделать text_icon_button и отнаследовать subheader

2024-04-08 11:22 UTC, artiebears13 commented on bin/gui/widgets/layouts/tab_header/tab_header_name_layout.py
> +class TabHeaderNameLayout(HorizontalLayout):
tab_header_main_layout

2024-04-08 11:30 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/dimensional_stats_label.py
> +        self.is_prev_void = self.value is None
cut all this, and rename check_empty

2024-04-08 11:32 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/drag_target_indicator.py
> +    A QLabel subclass representing a drop target indicator during drag and drop operations.
DropTargetIndicator

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/buttons/subheader_button.py
> +        self.setPixmap(QPixmap(str(ICONS_PATH.joinpath(self._icon))))
Вроде то же самое делается в ините TextIconButton, где self.pixmap = Pixmap(icon). И подразумевается, как я понял, что в self._icon записывается полный путь до иконки, а здесь еще один joinpath. 

joinpath кстати можно заменить на "/"

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/buttons/text_icon_button.py
> +        pos_x = 5  # hardcoded horizontal margin
![image](https://github.com/geoprotech/PowerEye_2/assets/57092435/c9e9edc9-1dc6-4bb4-acb0-bb8d32344b99)

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/enter_data/enter_data.py
> +        self.set_spacing(0)
set_spacing дважды

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/header/__init__.py
пустой инит

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/custom/dimensional_stats_custom_label.py
> +        self.name_label = DimensionalStatsCustomInnerLabel(parent=self, text=self.unit.name)
зачем это в self? Можно просто локальные переменные make() сделать

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/custom/dimensionless_num_stats_custom_label.py
> +        self.set_content_margins(0, 0, 0, 0)
дважды set_content_margins

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/custom/dimensional_stats_custom_label.py
> +        self.add_widget(self.name_label, alignment=Qt.AlignLeft)
мб это тоже в set_up_children засунуть как ниже?

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/custom/dimensionless_str_stats_custom_label.py
> +class DimensionlessStrStatsCustomLabel(HorizontalLayout):
Можно было просто отнаследоваться от DimensionlessStrStatsLabel и просто init с make переписать, но так тоже норм, думаю

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/custom/draggable_custom_stats_widget.py
> +            if isinstance(unit, TmpUnitDimLess):
можно в dict и пару функций обернуть

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/custom/draggable_custom_stats_widget.py
> +        self.drag.orderChanged.connect(print)
print стоит убрать

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/custom/stats_custom_container.py
> +WIDGET_WIDTH = DIMENSIONAL_STATS_LABEL_STYLESHEET.QLabel.width + 2  # type: ignore
поч тут +2

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/default/dimensional_stats_label.py
> +        self.name_label.setObjectName("lbl")
вот эти имена думаю можно убрать или поменять, если нужны все таки

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/default/combobox_stub.py
> +from ..combobox_stub import ComboboxStub
Все в default по аналогии с custom

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/stats_container.py
> +        scroll_area.setStyleSheet(
это нужно переместить в src.styles и тд

2024-04-24 14:45 UTC, TeeMan508 commented on bin/gui/widgets/layouts/stats/default/draggable_stats_widget.py
> +class DraggableStatsWidget(QWidget):
В эти классы стоит добавить методы по добавлению, изменению и удалению строк в статистике, будет полезно в будущем, но это скорее в TODO нужно прописать на некст спринт

2024-04-25 08:30 UTC, artiebears13 commented on bin/gui/widgets/buttons/subheader_button.py
> +        self.setPixmap(QPixmap(str(ICONS_PATH.joinpath(self._icon))))
исправил

2024-04-25 08:31 UTC, artiebears13 commented on bin/gui/widgets/layouts/enter_data/enter_data.py
> +        self.set_spacing(0)
исправил

2024-04-25 08:32 UTC, artiebears13 commented on bin/gui/widgets/layouts/header/__init__.py
исправил

2024-04-25 08:34 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/custom/dimensional_stats_custom_label.py
> +        self.name_label = DimensionalStatsCustomInnerLabel(parent=self, text=self.unit.name)
они используются в другихметодах класса

2024-04-25 08:36 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/custom/dimensional_stats_custom_label.py
> +        self.add_widget(self.name_label, alignment=Qt.AlignLeft)
сделал

2024-04-25 08:40 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/custom/dimensionless_str_stats_custom_label.py
> +class DimensionlessStrStatsCustomLabel(HorizontalLayout):
сделал

2024-04-25 08:40 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/custom/draggable_custom_stats_widget.py
> +            if isinstance(unit, TmpUnitDimLess):
?

2024-04-25 08:41 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/custom/stats_custom_container.py
> +WIDGET_WIDTH = DIMENSIONAL_STATS_LABEL_STYLESHEET.QLabel.width + 2  # type: ignore
+ границы

2024-04-25 08:44 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/default/dimensional_stats_label.py
> +        self.name_label.setObjectName("lbl")
сделал

2024-04-25 08:45 UTC, artiebears13 commented on bin/gui/widgets/layouts/stats/default/combobox_stub.py
> +from ..combobox_stub import ComboboxStub
?

2024-04-25 10:07 UTC, merged