made Unit class
geoprotech/PowerEye_2 pull request #18
Opened 2024-06-02 21:02 UTC by AliRN9

TODO стоят, где реализация связана с размерностями.

2024-06-04 09:57 UTC, TeeMan508 requested changes

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +    TYPE = Literal['depth', 'weight', 'corner', 'time']
length, force, torque, pressure, flowrate, angle, volume, velocity, time

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +    def check_dim(dim: str, type_dim: str) -> bool:
![image](https://github.com/geoprotech/PowerEye_2/assets/57092435/53f78c0e-8851-4dd0-a776-c4bd26981d02)

В Preprocessing есть словарь величин и соответствующие коэффициенты. Там же есть функция конвертирования величин

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +        self._dim = dim
Нейминг: _dimension, _dimension_type

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +            self._value, self._dim, self._type_dim  # type: ignore
Почему здесь type: ignore?

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +        self._type_dim = new_type_dim
Наверное без _, просто type_dim = new_type_dim

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +    def __ge__(self, other: Unit) -> bool:
Ну по идее нужно проверять величину в си, иначе такая логика выдаст что 1м < 10мм

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +            f'si_value = {self._si_value}, type_dimension = {self._type_dim})'
dimension_type =...

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +from __future__ import annotations
annotations где то используется?

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +        self.name = new_name  # type: ignore
type: ignore в присвоении атрибутов?

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +class BaseUnit(ABC):
Нужно разделить классы по файлам

2024-06-04 09:57 UTC, TeeMan508 commented on bin/gui/essentials/unit/unit.py
> +class UnitDimLess(BaseUnit):
DimensionlessUnit

2024-06-07 12:44 UTC, AliRN9 commented on bin/gui/essentials/unit/unit.py
> +from __future__ import annotations
да,  чтобы прописать Unit
def __ge__(self, other: Unit) -> bool:
     return bool(self._si_value >= other._si_value)

2024-06-08 10:31 UTC, TeeMan508 requested changes

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/essentials/unit/defolt.py
> +    def value(self, new_value: Union[float, int]) -> None:
Али, не надо ставить #type: ignore при любой ошибке mypy. Я же не просто так его в прекоммит добавил. Если mypy ругается, нужно подумать над типизацией. Если возникают вопросы, лучше спросить, а не просто игнорить ошибки mypy :(

Например здесь можно сделать реализацию через generic. Пример такой реализации: 


from typing import Generic, TypeVar, Union

T = TypeVar('T')


class Test(Generic[T]):
    def value(self, x: T):
        return 1


class UsageWithStrInt(Test[Union[str, int]]):
    def value(self, x: Union[str, int]) -> int:
        return 1


class UsageWithStrIntTuple(Test[Union[str, int, tuple]]):
    def value(self, x: Union[str, int, tuple]) -> int:
        return 1

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/essentials/unit/defolt.py
> +        self._value = tmp_convert(self._dimension_type, self._value, self._dimension, new_dimension)  # type:ignore
Аналогично

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/essentials/unit/defolt.py
> +        return tmp_convert_to_si(value, dimension, dimension_type)
Почему tmp

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/essentials/unit/defolt.py
> +        self._si_value = self.convert_to_si(self._value, self._dimension, self._dimension_type)  # type:ignore
#type: ignore

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/essentials/unit/defolt.py
> +        # тут возможно будет КЛАСС_РАЗМЕРНОСТИ.convert_to_si()
Не рудиментный комментарий?

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/essentials/unit/defolt.py
> +            raise TypeError(
Нужно сделать свои exception'ы для unit

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +import math
почему tmp?

По логике этот файл вообще должен лежать в unit и называться по типу converting.py

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +dimensions_coeff: dict[str, dict[str, Union[int, float]]] = {
Довольно лениво, копипаст из старой версии по сути. Предлагаю сделать Enum для полей типа {"m/s": 1, "km/h": 3.6, "mi/h": 2.2369, "in/s": 39.3701} и Enum для полей "velocity" и тд. Аналогично events и matches в моем пр по беку. 

Ну и нейминг здесь старый не к чему

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +dimensions_coeff: dict[str, dict[str, Union[int, float]]] = {
Дополняя, здесь, думаю, из базовых типов значений можно оставить только float, убрать int

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +    assert dimension_type in dimensions_coeff.keys(), f'Unprocessed measurement: {dimension_type}'
Мы отказались от assert'ов. Нужно прописать свои exception'ы

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +    return round(value * (dimensions_coeff[dimension_type][new_dim] / dimensions_coeff[dimension_type][current_dim]), 6)
Здесь можно использовать функцию convert_to_si, написанную выше)

2024-06-08 10:31 UTC, TeeMan508 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +    return round(value * (dimensions_coeff[dimension_type][new_dim] / dimensions_coeff[dimension_type][current_dim]), 6)
На этом все, перед следующем пр, проверь все еще раз самостоятельно на предмет невнимательности)

2024-06-08 10:40 UTC, AliRN9 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +import math
потому, что я полагаю что это временная реализация. До полноценного класса с размерностями

2024-06-08 10:44 UTC, TeeMan508 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +import math
Так часть таска по unit проработать логику конверта, тем более что она уже реализована в старой версии. Достаточно оформить, как я написал ниже

2024-06-08 10:47 UTC, AliRN9 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +import math
по типу как  в старом проектe класс DImension, где реализована вся логика размерностей

2024-06-08 10:54 UTC, TeeMan508 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +import math
Вроде определились, что у нас не будет глобальной размерности в приложении, а она будет привязана к каждому полю отдельно.

2024-06-08 11:00 UTC, AliRN9 commented on bin/gui/tmp_dimension/tmp_dimension.py
> +import math
я об этом не помню))
ну если так, то согласен

2024-06-13 11:20 UTC, AliRN9 commented on bin/gui/essentials/unit/dimensional.py
> +    def value(self) -> Union[float, int]:
добавил его чтобы mypy не  обойти(без геттара, сеттар не работает)
https://github.com/python/mypy/issues/5936

2024-06-16 11:32 UTC, TeeMan508 requested changes

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/convert.py
> +import math
Пример реализации через enum. В этом случае даже dimension_type не нужен по идее

`class Dimension(float, Enum):
    """
    blablabla
    """


class Velocity(Dimension):
    m_per_s: float = 1.
    km_per_h: float = 3.6
    mil_per_h: float = 2.2369
    in_per_s: float = 39.3701


class Length(Dimension):
    m: float = 1.
    km: float = 0.0001
    inch: float = 123.


def convert_to_si(value: float, dim_from: Dimension) -> float:
    return value / dim_from


def convert(value: float, dim_from: Dimension, dim_to: Dimension) -> float:
    assert type(dim_from) is type(dim_to)

    return convert_to_si(value, dim_from) * dim_to


if __name__ == "__main__":
    vel = 10.  # km/h
    converted_vel = convert(vel, Velocity.km_per_h, Velocity.m_per_s)
    print(converted_vel)`

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/widgets/line_edits/dimensional_line_edit/dimensional_line_edit.py
> +            if '.' in text:
Это по пр Артема, полагаю

2024-06-16 11:32 UTC, TeeMan508 commented on bin/exceptions/gui/__init__.py
> +from .essentials import *
Файловую структуру exceptions нужно вернуть как было. пока непонятно зачем еще доп директория essentials в которой одна папка unit с одним файлом исключения. Выглядит излишне

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/dimensional.py
> +        self._dimension_type = new_dimension_type
все еще непон почему тут сетится в _dimension_type, если есть проперти dimension_type

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/dimensional.py
> +if __name__ == "__main__":
name==main нужно будет убрать

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/dimensional.py
> +        self._value = DimensionsConvert.convert_dimension(
DimensionsConvert.convert_dimension, стоит подумать над неймингом...

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/convert.py
> +import math
Здесь же пример как НЕ передовать в функцию конверта одновременно и value и value_si. Потому что это абсолютно нелогично. Нахрена вообще нужно value в аргументах функции, если передается value_si и наооборот.

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/convert.py
> +import math
Предлагаю также не объединять все эти функции в класс.

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/convert.py
> +            raise UnitDimensionException(f'{dimension_type} is missing DimensionsConvert', 'warn')
Можно первые 4 строки убрать

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/convert.py
> +        if dimension_type == "datetime":
а datetime вообще нету в типах размерностей

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/dimensional.py
> +    TYPE = Literal["length", "force", "torque", "pressure", "flowrate", "angle", "volume", "velocity", "time"]
см предложенный код

2024-06-16 11:32 UTC, TeeMan508 commented on bin/gui/essentials/unit/dimensional.py
> +    TYPE = Literal["length", "force", "torque", "pressure", "flowrate", "angle", "volume", "velocity", "time"]
+ еще нужен ребейз после этих изменений

2024-06-16 12:38 UTC, AliRN9 commented on bin/gui/essentials/unit/convert.py
> +import math
Во первых надо общаться более корректно, а не со словами  нахрена   и  абсолютно нелогично.
Во вторых можно увидеть что я передаю туда value, чтобы вернуть если на вход придут одинаковые размерности.  
Можно сказать, что проверка излишне или что ее можно сделать перед обращением к функции.

и чем эта реализация лучше?
dimension_type используется для проверки 

converted_vel = convert(vel, Velocity.km_per_h, Velocity.m_per_s) так не получится передать, потому что размерности будут строками 
converted_vel = convert(vel, Velocit[km_per_h], Velocity[m_per_s]) в лучшем случае это будет так при том, что нужно будет установить, что тип  размерности  'Velocity', которая строка  это  Enum  Velocity

2024-06-16 17:15 UTC, AliRN9 commented on bin/gui/essentials/unit/dimensional.py
> +        self._dimension_type = new_dimension_type
потому что нет  ceтера для  _dimension_type, потому что если нельзя в юните просто изменить тип_размерности
Можно изменить все  по отдельности кроме типа размерности, либо изменить все сразу в функции set 
и поэтому тут стоит  self._dimension_type = new_dimension_type, а потом сетар для  dimension который проверяет существование типа размерности  и 
 соответствует ли заданная размерность типу размерности 
 Логика в том, что основной параметр это тип размерности на основе которого задается размерность и если нужна новая размерность нужно создать новый обьект.(прост не вижу ситуацию, когда длинна 5m может стать объемом 5m)
Либо наверное можно сделать сетер для  dimension_type и там реализовать  проверку на существование заданного типа размерности и проверку  соответствует ли  заданный  тип размерности   существующей размерности

2024-06-16 17:15 UTC, AliRN9 commented on bin/gui/essentials/widgets/line_edits/dimensional_line_edit/dimensional_line_edit.py
> +            if '.' in text:
да

2024-06-16 17:21 UTC, AliRN9 commented on bin/exceptions/gui/__init__.py
> +from .essentials import *
Тут согласен 
Надо будет обсудить как это можно сделать более удобным
в моменте станет тяжело  понять какой exceptions  к чему относится

2024-06-17 08:30 UTC, TeeMan508 commented on bin/gui/essentials/unit/convert.py
> +import math
Предлагаю one-to-one завтра, во сколько тебе удобно?

2024-06-17 08:48 UTC, AliRN9 commented on bin/gui/essentials/unit/convert.py
> +import math
С 11 до 20

2024-06-17 10:49 UTC, TeeMan508 commented on bin/gui/essentials/unit/convert.py
> +import math
Тогда в 11

2024-07-10 14:23 UTC, merged