added graphs tabs
geoprotech/PowerEye_2 pull request #20
Opened 2024-06-06 10:37 UTC by artiebears13

Добавил вкладки с графиками

2024-06-08 11:28 UTC, TeeMan508 requested changes

2024-06-08 11:28 UTC, TeeMan508 commented on bin/gui/essentials/widgets/graph_meta/buttons/graph_preferences_button/graph_preferences_button.py
Я бы еще зарефакторил структуру в essentials. Все таки в этой директории я так понял мы хотим иерархию виджет-> подмодуль. А то сейчас есть buttons и есть graph_meta.buttons

2024-06-08 11:28 UTC, TeeMan508 commented on bin/gui/essentials/widgets/graph_meta/layouts/figure_preferences/figure_preferences.py
> +        if settings_widget is None:
Мб его сразу по дефолту = [] сделать?

2024-06-08 11:28 UTC, TeeMan508 commented on bin/gui/essentials/widgets/graph_meta/layouts/figure_preferences/figure_preferences.py
> +        self.setObjectName("preferences")
А корректно ли в base класс setObjectName делать?

2024-06-08 11:28 UTC, TeeMan508 commented on bin/gui/essentials/widgets/graph_meta/layouts/figure_preferences/figure_preferences.py
> +    def set_up_buttons(self) -> None:
Нужно его сделать абстрактным, думаю

2024-06-08 11:28 UTC, TeeMan508 commented on bin/gui/essentials/widgets/graph_meta/layouts/main/graph_meta.py
> +"""
1. Привязать к каждому полю Unit и по кнопке доставать, них значения при изменении, складывать в storage и эмитить graph object. Потом из него graph object заберет по эмиту
2. On_click разве что 
3.  Обсудили на созвоне

2024-06-08 11:28 UTC, TeeMan508 commented on bin/gui/modules/mask_group_graph/figure_preferences/figure_preferences.py
> +from PySide6.QtWidgets import QWidget
Полагаю, что mask_group_graph это diffstick должен быть. И нужно в init каждого подмодуля прокинуть главный объект. Чтобы можно было из сабмодуля его импортировать

2024-06-08 11:28 UTC, TeeMan508 commented on bin/gui/modules/trajectory/figure_preferences/figure_preferences.py
> +from bin.gui.essentials.widgets.layouts.base_vertical_layout import VerticalLayout
Ну все остальное аналогично в целом. Хочу попросить еще в descent_parameters эту же логику реализовать. Получилось довольно удобно и чисто, лайк

2024-06-11 13:27 UTC, artiebears13 commented on bin/gui/essentials/widgets/graph_meta/buttons/graph_preferences_button/__init__.py
> +from .graph_preferences_button import GraphPreferencesButton
fixed

2024-06-11 13:34 UTC, artiebears13 commented on bin/gui/essentials/widgets/graph_meta/layouts/figure_preferences/figure_preferences.py
> +        if settings_widget is None:
no

2024-06-11 13:35 UTC, artiebears13 commented on bin/gui/essentials/widgets/graph_meta/layouts/figure_preferences/figure_preferences.py
> +    def set_up_buttons(self) -> None:
done

2024-06-11 13:35 UTC, artiebears13 commented on bin/gui/essentials/widgets/graph_meta/layouts/figure_preferences/figure_preferences.py
> +        self.setObjectName("preferences")
yes

2024-06-14 08:43 UTC, TeeMan508 requested changes
Comments in telegram

2024-06-14 11:46 UTC, merged