create localization algo and baseline
geoprotech/PowerEye_2 pull request #21
Opened 2024-06-27 06:39 UTC by artiebears13

Сделал бейзлайн. Главное:

- переводы в json файлах
- постфикс json файла - язык на который перевод
- для билда переводов необходимо запустить скрипт ```create_translation.py```
- для смены языка пока предусмотрен такой способ: в ```main_window.py``` в ините поменять самому

2024-06-27 06:44 UTC, artiebears13 commented
Продолжение:
- в json поле context - имя класса, где будет вызываться перевод
- за вызов перевода ответственнен метод ```self.tr``` у всех классов отнаследованных от QObject
- соответственнно я думаю что класс Unit надо будет также отнаследовать от QObject

2024-07-10 15:35 UTC, TeeMan508 requested changes

2024-07-10 15:35 UTC, TeeMan508 commented on create_translation.py
> +import os
нужно добавить этот файл в bin/utils

2024-07-10 15:35 UTC, TeeMan508 commented on create_translation.py
> +        content += f'    <message>\n        <source>{src}</source>\n        <translation>{trans}</translation>\n    </message>\n'
пробелы можно заменить на \t

2024-07-10 15:35 UTC, TeeMan508 commented on create_translation.py
> +        print(f"{dirs=}")
Принты нужно будет убрать к финальной версии

2024-07-10 15:37 UTC, TeeMan508 commented
По наследование unit от qobject не уверен, все таки объект unit создается в каком то модуле и там можно прописать self.tr этого модуля

2024-07-17 08:23 UTC, artiebears13 commented
В последнем коммите переделал кнопку чтобы она подгонялась под текст и подобавлял переводов

2024-07-22 13:42 UTC, TeeMan508 requested changes
Нужно доделать предыдущие комментарии.

По мелким правкам:

Здесь вместо "предпочтения" поставить "настройки"
![image](https://github.com/user-attachments/assets/0503aec4-4e48-4a44-b155-db8bf8191498)

Здесь не переведены параметры, не влезает дюйм и левая надпись "тест" 
![image](https://github.com/user-attachments/assets/a6e3afb2-cc8c-4b91-873f-70429f79ddf1)

Нужно еще поиграться мб с паддингами, а то не по центру некоторые слова стоят
![image](https://github.com/user-attachments/assets/7a26d4a2-df13-41df-91fa-f0ab1a34338e)

2024-07-30 01:06 UTC, merged