refactor stats
geoprotech/PowerEye_2 pull request #22
Opened 2024-07-21 13:45 UTC by AliRN9

1. Fix bug при переносе ячеек.
2. Глобальный рефактор модуля:
 с удалением лишних файлов;
 объединение классов размерности в базовом классе;
  удаление реализации методов  в базовых классах.

2024-07-22 13:57 UTC, TeeMan508 requested changes
Предлагаю еще сразу все отцентрировать и поправить надпись default statistics справа(по идее должна быть custom).

![image](https://github.com/user-attachments/assets/25af9f83-31a2-41ac-83b6-1b1f8bdd4a39)

2024-07-22 13:57 UTC, TeeMan508 commented on bin/gui/modules/stats/drag_widget/base/drag_widget/drag_widget_base.py
>      def __init__(self, orientation: Qt.Orientation = Qt.Orientation.Horizontal, number: int = 13):
предлагаю number зарефакторить в number_of_widgets

2024-07-22 13:57 UTC, TeeMan508 commented on bin/gui/modules/stats/drag_widget/base/drag_widget/drag_widget_base.py
> +        self.make()
предлагаю обернуть в init_protocol раз все равно вызываем make и pre_setup. Я на своей ветке написал такой декоратор только без show, назвал quet_init_protocol

2024-07-22 13:59 UTC, TeeMan508 commented on bin/gui/modules/stats/drag_widget/base/drag_widget/drag_widget_base.py
> +        self.make()
@artiebears13 посмотри тоже пр плз на предмет неточностей

2024-07-29 11:43 UTC, artiebears13 commented on bin/gui/modules/stats/drag_widget/base/drag_widget/drag_widget_base.py
> +        self.make()
@TeeMan508 все ок

2024-09-09 09:32 UTC, closed without merging