logging setup
geoprotech/PowerEye_2 pull request #25
Opened 2024-08-07 08:16 UTC by AliRN9

Запись идет в один единый файл и для бэк и для фронта, с обозначением процессора запуска и pid процессора.
Не видел большого смысла в разделение по файлам, так как придется знать какой модуль записываем, и создавать два логгера, а тут по процессору можно понять, какая часть логирируется.
Вся конфигурация для логгера задается в одном файле  logging_config.py

2024-08-09 09:23 UTC, TeeMan508 commented on .gitignore
![image](https://github.com/user-attachments/assets/5cabfd57-3347-4cec-9534-84412f3164aa)

Предлагаю вместо PID писать backend и frontend соответственно, а также убрать MainProcess и Process-1(непонятно за что эта инфа отвечает)

2024-08-09 09:24 UTC, TeeMan508 commented on .gitignore
+ еще предлагаю добавить расширение файла в названии файла, где возникла ошибка

2024-08-09 09:25 UTC, TeeMan508 commented on .gitignore
+ непонятно, что такое exc_info

2024-08-09 09:26 UTC, TeeMan508 commented on bin/connection/setup.py
> +logger = logging.getLogger(__name__)
Мб как то можно сделать синглтон, чтобы вместо прописывания в каждом файле 'logger = ' импортить просто класс и вызывать его? По моему так будет удобнее

2024-08-09 09:26 UTC, TeeMan508 commented on bin/connection/setup.py
> +    # frontend_handler.test_log()
Этот коммент лучше убрать

2024-08-09 09:27 UTC, TeeMan508 commented on bin/exceptions/level.py
> +    WARNING = 'warning'
Есть же WARN. Надо оставить что то одно тогда

2024-08-09 09:27 UTC, TeeMan508 commented on bin/exceptions/level.py
> +    NOTSET = "notset"
Зачем нужен NOTSET?

2024-08-09 09:28 UTC, TeeMan508 commented on bin/log/logging_config.py
> +            "maxBytes": 5120000,  # Максимальный размер файла 5 MB
го тут 10мб, либо оставить 5 если файл при каждом запуске чистится

2024-08-09 09:29 UTC, TeeMan508 commented on bin/exceptions/level.py
> +name_to_level = {
Вот тут не понял смысл этой мапы. Можно же прямо в значения Level записать logging.CRITICAL и тд

2024-08-09 09:30 UTC, TeeMan508 commented on bin/exceptions/base_powereye_exception.py
> +        logger.log(level_int, text, exc_info=except_info)
Тут непонятно что такое except_info, надо где то написать в качестве коммента

2024-08-09 09:32 UTC, TeeMan508 commented on .gitignore
папку log предлагаю переименовать в logger и переместить в utils.
А сам .лог файл переместить в etc/logs

2024-08-09 09:34 UTC, TeeMan508 commented on bin/exceptions/base_powereye_exception.py
> +from bin.log import logging_config  # noqa
Почему везде импортируется конфиг с noqa

2024-08-09 09:41 UTC, AliRN9 commented on .gitignore
А зачем расширение? 
У нас везде же py файлы

2024-08-09 09:44 UTC, TeeMan508 commented on .gitignore
Чтобы наглядно было понятно, что это файл, а не название функции, например. Чтобы когда смотришь на логи, все было прозрачно

2024-08-09 09:45 UTC, TeeMan508 commented on bin/log/logging_config.py
> +            "maxBytes": 5120000,  # Максимальный размер файла 5 MB
Сейчас затестил -  не чистится, стоит сделать чтобы чистился при запуске, думаю. Иначе лог файл будет бесконечно расти, а это не особо нужно

2024-08-09 09:47 UTC, AliRN9 commented on .gitignore
MainProcess это основной процесс( у нас вроде фронт на нем крутится), Process-1 это бэк( он из под коробки так работает посмотрю можно переопределить, но мне кажется это излишне
Pid процессора при каждом запуске разные

2024-08-09 09:48 UTC, TeeMan508 commented
Так сделано довольно чисто, предлагаю еще реализовать 2 разных лога - для бека и фронта отдельно в дополнение к существующему общему логу.

2024-08-09 09:53 UTC, AliRN9 commented on bin/connection/setup.py
> +logger = logging.getLogger(__name__)
Он работает как синглтон, из под коробки, он находит существующий логгер при функции getlogger(__name__)

2024-08-09 09:54 UTC, AliRN9 commented on bin/exceptions/level.py
> +    WARNING = 'warning'
Я прост посмотрел, как в библиотеке logging сделано и взял все их нейминги

2024-08-09 09:55 UTC, TeeMan508 commented on bin/connection/setup.py
> +logger = logging.getLogger(__name__)
Тогда непонятно зачем logging_config каждый раз импортировать

2024-08-09 09:56 UTC, AliRN9 commented on bin/log/logging_config.py
> +            "maxBytes": 5120000,  # Максимальный размер файла 5 MB
Тут можно дописать скрипт, который чистит при каждом запуске, в целом думал так сделать
Но ставить флаг w, нельзя так как у нас работает два процессора, иначе каждый процессор при запуске стирать будет

2024-08-09 09:57 UTC, AliRN9 commented on bin/exceptions/base_powereye_exception.py
> +        logger.log(level_int, text, exc_info=except_info)
Это если в логгер  мы хотим саму информацию ошибку записать, как в терминале

2024-08-09 09:58 UTC, AliRN9 commented on bin/exceptions/base_powereye_exception.py
> +from bin.log import logging_config  # noqa
Он применяют все заданные настройки в конфиге, иначе они слетают 
Попробую скрыть его

2024-08-09 11:16 UTC, TeeMan508 commented on .gitignore
Я понимаю, что pid разные - их писать и нет смысла. Просто переопределить MainProcess и Process-1 во Frontend и Backend - это более наглядно. (по аналогии с логами докера)

2024-08-09 12:36 UTC, AliRN9 commented on bin/exceptions/base_powereye_exception.py
> +from bin.log import logging_config  # noqa
он применяет центральную конфигурацию, его импортируешь чтобы задать конфигурацию, он нигде явно не применяется, но без импорта конфигурация слетает поэтому  # noqa

2024-08-09 12:40 UTC, AliRN9 commented on bin/exceptions/level.py
> +name_to_level = {
это чтобы если мы в эксепшн ловим, то записываем тоже в логгер, для этого мне нужно по level.info понять какой log.info 
Этот словарь применяется BasePowereyeException

2024-08-09 12:43 UTC, AliRN9 commented on bin/exceptions/level.py
> +    NOTSET = "notset"
Я прост посмотрел, как в библиотеке logging сделано и взял все их нейминги

2024-08-09 12:46 UTC, AliRN9 commented on .gitignore
pid  единственное, где нужно если мы хотим еще в терминале видеть какой процесс, оставил его с такой логикой

2024-08-09 12:47 UTC, AliRN9 commented on .gitignore
Просто переопределить MainProcess и Process-1 во Frontend и Backend - это более наглядно. (по аналогии с логами докера) тут согласен
Правлю

2024-08-10 06:51 UTC, TeeMan508 commented on bin/exceptions/level.py
> +name_to_level = {
""Можно же прямо в значения Level записать logging.CRITICAL и тд""

2024-08-10 20:09 UTC, AliRN9 commented on bin/exceptions/level.py
> +name_to_level = {
и вправду))
тупанул))

2024-08-14 12:46 UTC, artiebears13 commented on main.py
> +def pre_start():
ренейм на parse_flags

2024-08-14 12:46 UTC, artiebears13 commented on main.py
> +    parser.add_argument(
подумать мб как то можно красиво сделать на случай масштабирования

2024-08-14 12:46 UTC, artiebears13 commented on main.py
> +    parser.add_argument(
мб вынести в utils/parser

2024-08-14 12:46 UTC, artiebears13 commented on poetry.lock
> +    {file = "pandas-2.2.2-cp310-cp310-macosx_11_0_arm64.whl", hash = "sha256:c7adfc142dac335d8c1e0dcbd37eb8617eac386596eb9e1a1b77791cf2498238"},
добавить poetry.lock в .gitignore

2024-08-16 14:27 UTC, TeeMan508 requested changes

2024-08-16 14:27 UTC, TeeMan508 commented on main.py
> +def pre_start():
тут не исправлено

2024-08-16 14:27 UTC, TeeMan508 commented on main.py
> +    parser.add_argument(
тут тоже

2024-08-16 14:27 UTC, TeeMan508 commented on main.py
> +def pre_start():
лучше кста ренейм в parser_setup

2024-08-16 14:27 UTC, TeeMan508 commented on main.py
> +    clear_log_name = namespace.clear_logs
![image](https://github.com/user-attachments/assets/8db5fa49-3388-4b89-968d-5721a74bfc8f)

2024-08-16 14:27 UTC, TeeMan508 commented on main.py
> +def pre_start():
И лучше эту функцию перенести в utils/parser/setup.py, а в мейн просто импортировать

2024-08-16 14:27 UTC, TeeMan508 commented on bin/gui/modules/main/main_layout/main_layout.py
> +logger = get_logger(__name__)
Аналогично предлагаю сделать синглтон класс, который можно было бы просто вызывать, а не заводить в каждом файле переменную. Или так сделать не получится?

2024-08-16 14:27 UTC, TeeMan508 commented on bin/exceptions/level.py
> +    WARN = logging.WARNING
Давай все таки оставим один варнинг)

2024-08-16 14:27 UTC, TeeMan508 commented on bin/exceptions/level.py
> +    NOTSET = logging.NOTSET
Предлагаю убрать лишние уровни - Notset и Fatal

2024-08-16 14:32 UTC, AliRN9 commented on bin/gui/modules/main/main_layout/main_layout.py
> +logger = get_logger(__name__)
я же писал, что он работает как синглтон, из под коробки, он находит существующий логгер при функции getlogger(name)

2024-08-16 14:37 UTC, AliRN9 commented on bin/gui/modules/main/main_layout/main_layout.py
> +logger = get_logger(__name__)
он по имени находит логгер и дописывает в него 
А прост инициализируем  функцией get_logger

2024-08-16 14:42 UTC, AliRN9 commented on main.py
> +    clear_log_name = namespace.clear_logs
я не понял в чем прикол подчеркивания пайчармом этого, но если тыкнуть на add fixture ..... то все норм

2024-08-19 07:00 UTC, TeeMan508 commented on bin/utils/console_parser/setup.py
> +class FlagParserConsole(argparse.ArgumentParser):
ArgsParser + имя директории args_parser и я мерджу в дебаг

2024-08-19 10:40 UTC, merged