write EnterData class
geoprotech/PowerEye_2 pull request #26
Opened 2024-08-10 08:57 UTC by artiebears13

- Написал EnterData
- добавил исключение ошибки flake8, тк black автоматически рефачил строку а flake не пропускал ее (перенос формул)

2024-08-16 15:38 UTC, TeeMan508 requested changes

2024-08-16 15:38 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +    def calc_flow_rate(self) -> Union[int, float]:
предлагаю эти методы сделать void(чтобы сетили поля, а не возвращали значения)

2024-08-16 15:38 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +        # TODO: rename parameters
Это входит в таск

2024-08-16 15:38 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +        self.__check_value(value, "Hole depth", MAX_METER_VALUE)
Тут предлагаю эти опорные значения записать в enum и этот enum добавить в private поле класса(либо enum в этом же файле сверху оставить)

2024-08-16 15:38 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +    @field.setter
Все таки странно выходит для каждого вручную пописывать сеттер, очень трудолюбиво). Check value же метод универсальный. Таким образом можно сделать мапу для каждого поля сопостовлять проверку. И далее универсальным сеттером делать эту проверку просто. Те можно все таки сделать гораздо короче по коду. 

Если расширить - в эту мапу можно записывать не только аргумент фаункции, но и саму функцию проверки(например если появится специфическое поле.)

2024-08-16 15:38 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +    @field.setter
```
Пример:

class EnterDataField(TypedDict):
    value: Any
    validation_function: Oprional[Callable[..., Any]]
    args: Any

class EnterDataFields(Enum):
         WELL: EnterDataField = {"value": "71Г", "validation_function": EnterData.check_value; "args": MAX_VALUE}

Таким образом:

class EnterData:

    def __setattr__(self, attr):
        if attr not in EnterDataFields.keys(): raise тырм пырым
        validation_function =  EnterDataFields[attr][validation_function]
        args =  EnterDataFields[attr][args]
        validation_function(args)
        setattr(self, attr)

```

Это касаемо сеттеров. Аналогично с гетерами. Более того, изначально можно завести метод __init_values и вызвать его в __init__, который будет сетить дефолтные параметры сразу(таким образом инициализируя все аттрибуты первоначально).


Таким образом, сеттинг и геттинг всех полей займет гораздо меньше строк

2024-08-16 15:38 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +            print("Not enough data for low_block_position, high_block_position")
На все такие принты нужны свои эксепшны с лвлом инфо

2024-08-16 15:47 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +    @field.setter
Ну это примерный вариант, первое что пришло в голову, если подумать, можно думаю еще что-нибудь красивое сюда допилить)

2024-08-19 08:04 UTC, artiebears13 commented on bin/backend/modules/enter_data/enter_data.py
> +ENTER_DATA_FIELDS = {
оставить сеттеры геттеры

2024-08-19 08:10 UTC, artiebears13 commented on bin/backend/modules/enter_data/enter_data.py
> +        # TODO: rename parameters
скип

2024-08-19 08:11 UTC, artiebears13 commented on bin/backend/modules/enter_data/enter_data.py
> +    @field.setter
скип

2024-08-23 09:26 UTC, TeeMan508 requested changes

2024-08-23 09:26 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +            EnterDataInputFields.column_diameter.name in values  # type: ignore
Предлагаю отдельный raise на отсутствие колонок с уровнем дебаг

2024-08-23 09:26 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +                raise EnterDataValidationException(
тут лвл еррор

2024-08-23 09:26 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +            and EnterDataInputFields.casing_wall_thickness.name in values  # type: ignore
Аналогично

2024-08-23 09:26 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +    def check_values(self) -> Tuple[bool, List[str]]:
Это рудимент, я так полагаю

2024-08-23 09:26 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +    def get_dict(self) -> dict[str, Any]:
get_data можно

2024-08-23 09:26 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +        if 'column_diameter' in values and value >= values['column_diameter']:
ну и тут аналогичную проверку с уровнем дебаг нужно

2024-08-23 09:26 UTC, TeeMan508 commented on bin/backend/modules/enter_data/enter_data.py
> +            raise EnterDataValidationException("casing_wall_thickness must be less than column_diameter")
аналогично еррор(error - уровень, когда к ошибке привело некорректное действие пользователя, дебаг - когда ошибка возникло из-за ошибки разраба, инфо - принты, critical - когда ошибка вызывает краш программы)

2024-08-27 08:02 UTC, merged