Diffstick
geoprotech/PowerEye_2 pull request #29
Opened 2024-08-15 16:02 UTC by igorenkov

Module for differential sticking, weights and pipe load calculation. Contains several stubs for pandas.DataFrame columns that must be removed after Tim's merge.

2024-08-16 08:49 UTC, TeeMan508 requested changes
Чуть мелких правок, но в целом апрув.

2024-08-16 08:49 UTC, TeeMan508 commented on bin/backend/modules/deep_predictor/utils.py
> +"""Utils for data postprocessing"""
предлагаю это в bin/utils/deep_predictor

2024-08-16 08:49 UTC, TeeMan508 commented on bin/backend/modules/raw_data/data_fields.py
> +@unique
Это нужно будет чуть позже отредачить после мерджа SKRS-329

2024-08-19 10:51 UTC, TeeMan508 commented
@igorenkov смерджил код с названиями колонок

2024-08-21 17:39 UTC, igorenkov commented
Исправил колонки и переместил. Тимофей, проверь на всякий

2024-08-21 19:23 UTC, TeeMan508 commented
Вроде все четко, если что отладим на дебаге. 

Попрошу только сделать ребейз и я сквошну все и смержу в дебаг

2024-08-22 05:30 UTC, igorenkov commented
Я сделаль, можешь мержить

2024-08-22 07:02 UTC, merged