Artmed
geoprotech/PowerEye_2 pull request #4
Opened 2024-02-14 12:54 UTC by artiebears13

2024-02-15 12:12 UTC, TeeMan508 requested changes

2024-02-15 12:14 UTC, TeeMan508 commented on src/styles/components/widgets/line_edit/base/object.py
> +with open(CUR_PATH / Path("style.css")) as f:
и еще цвет не тот у границ 
![image](https://github.com/geoprotech/PowerEye_2/assets/57092435/242f133a-ef32-4728-82f5-1d2a61539c2c)

2024-02-19 07:52 UTC, artiebears13 commented on bin/gui/widgets/buttons/close_button.py
> +from src.styles.components.widgets.buttons import close_button_qss
Исправил

2024-02-19 07:52 UTC, artiebears13 commented on bin/gui/widgets/buttons/maximize_button.py
> +        self.setIcon(QIcon(str(ICONS_PATH.joinpath(icons.maximize_button_icon))))
Исправил

2024-02-19 07:54 UTC, artiebears13 commented on bin/gui/widgets/buttons/minimize_button.py
> +from src.styles.components.widgets.buttons import close_button_qss
![image](https://github.com/geoprotech/PowerEye_2/assets/84243070/a2241825-4b7c-4ebc-9c2d-aa12f9720ba0)
они привязаны к таким методам окна

2024-02-19 08:00 UTC, artiebears13 commented on bin/gui/widgets/checkboxes/base.py
> +from src.styles.components.widgets.checkboxes import CHECKBOX_STYLESHEET
исправил

2024-02-19 08:00 UTC, artiebears13 commented on bin/gui/widgets/checkboxes/base.py
> +class BaseCheckBox(QCheckBox):
?

2024-02-19 08:08 UTC, artiebears13 commented on bin/gui/widgets/checkboxes/base.py
> +        except RuntimeError:
тоже обсудим

2024-02-19 08:09 UTC, artiebears13 commented on bin/gui/widgets/checkboxes/base.py
> +        self, parent: QWidget, text: str, on_state_changed: Callable or None = None, tooltip: str or None = None
исправил, обсудим

2024-02-19 08:11 UTC, artiebears13 commented on bin/gui/widgets/labels/base.py
> +    def post_setup(self):
исправил

2024-02-19 08:12 UTC, artiebears13 commented on bin/gui/decorators/init_protocol.py
> +        self.post_setup()
?

2024-02-19 08:13 UTC, artiebears13 commented on bin/gui/widgets/labels/base.py
> +        make(): Function to create button. Must be overwritten.
упс

2024-02-19 08:14 UTC, artiebears13 commented on bin/gui/widgets/labels/base_image_label.py
> +from src.styles.components.widgets.labels import IMAGE_LABEL_STYLESHEET
done

2024-02-19 08:15 UTC, artiebears13 commented on bin/gui/widgets/labels/base_image_label.py
> +    Base abstract class for all labels.
обсудим

2024-02-19 08:23 UTC, artiebears13 commented on bin/gui/widgets/labels/base.py
> +    def reset_text(self, text: str) -> None:
удалил

2024-02-19 08:23 UTC, artiebears13 commented on bin/gui/widgets/labels/base_image_label.py
> +    def __init__(self, parent=None, text="", pixmap: QPixmap or None = None):
обсудим

2024-02-19 08:25 UTC, artiebears13 commented on bin/gui/widgets/labels/base_image_label.py
> +        self.pixmap = pixmap
fixed

2024-02-19 08:26 UTC, artiebears13 commented on bin/gui/widgets/layouts/header_layout.py
> +from bin.storage import Storage
так мы твой же берем

2024-02-19 08:27 UTC, artiebears13 commented on bin/gui/widgets/layouts/header_layout.py
> +        buttons_layout.setFixedWidth(120)
обсудим

2024-02-19 08:28 UTC, artiebears13 commented on bin/gui/widgets/layouts/header_layout.py
> +        # self.setFixedHeight(45)
исправил

2024-02-19 08:28 UTC, artiebears13 commented on bin/gui/widgets/layouts/main_layout.py
> +        self.set_spacing(0)
пока не знаю

2024-02-19 08:30 UTC, artiebears13 commented on bin/gui/widgets/layouts/main_layout.py
>          self.set_content_margins(0, 0, 0, 0)
обсудим

2024-02-19 08:30 UTC, artiebears13 commented on bin/gui/widgets/layouts/main_workspace.py
> +from .playground import PlaygroundLayout
да

2024-02-19 08:32 UTC, artiebears13 commented on bin/gui/widgets/line_edit/base.py
> +        make(): Function to create button. Must be overwritten.
исправил

2024-02-19 08:32 UTC, artiebears13 commented on bin/gui/widgets/line_edit/base.py
> +    def __init__(self, parent, *args, **kwargs):
исправил

2024-02-19 08:37 UTC, artiebears13 commented on src/styles/components/widgets/line_edit/base/object.py
> +with open(CUR_PATH / Path("style.css")) as f:
обсудим

2024-02-25 10:47 UTC, TeeMan508 commented on bin/gui/widgets/labels/image_label.py
> +        self._pixmap = self._pixmap.scaled(200, 200)
Вот здесь может как-то из геометрии scale задавать для картинки? Например под размер самого лейбла скейлить чтобы размер лейбла совпадал с размером картинки

2024-02-25 10:47 UTC, TeeMan508 commented on bin/gui/widgets/labels/image_label.py
> +        reset_text(): Function to reset text
set_text лучше раз все остальное set_... функциями обзываем

2024-02-25 10:47 UTC, TeeMan508 commented on bin/gui/widgets/line_edit/base.py
> +from bin.gui.decorators.init_protocol import init_protocol
Мб этот декоратор в модуль gui просто протянуть через __init__.py файлы, а то он часто импортится

2024-02-25 10:47 UTC, TeeMan508 commented on bin/gui/widgets/labels/image_label.py
> +        if self._pixmap:
Вроде определились эти проверки в сами set_... методы засунуть

2024-02-25 10:47 UTC, TeeMan508 commented on bin/gui/widgets/radiobuttons/base.py
> +        if text:
![image](https://github.com/geoprotech/PowerEye_2/assets/57092435/a7328e59-9312-4d53-a349-d4facecbd998)

2024-02-25 10:47 UTC, TeeMan508 commented on src/styles/components/widgets/layouts/header/style.css
>  QWidget #header{
нужно еще насчет этих имен обсудить, нужно определиться будем юзать или нет. Или частично, но тогда определить случаи когда будем использовать

2024-02-25 10:47 UTC, TeeMan508 commented on src/styles/components/widgets/layouts/header/style.css
> +    border-bottom: 1px solid gray;
#92D4D8

2024-02-25 10:57 UTC, TeeMan508 commented on src/styles/components/widgets/layouts/header/style.css
> +    border-bottom: 1px solid gray;
![image](https://github.com/geoprotech/PowerEye_2/assets/57092435/d3106315-4bf7-4326-8229-4d326b2c412f)
Вот тут еще из make в pre_setup нужно переместить, а сам make сделать абстрактным

2024-02-28 10:01 UTC, merged