Create pop up windows
geoprotech/PowerEye_2 pull request #5
Opened 2024-02-23 23:23 UTC by AliRN9

Жду разнос, парни
@TeeMan508 
@artiebears13

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/alert_popup.py
> +        self, parent: QWidget, layout_type_body: Literal["HBox", "VBox"], title: str, alert_text: str, **kwargs
не вижу смысла предоставлять выбор тк всегда будет Vertical

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/alert_popup.py
> +class AlertPopUp(BasePopUp):
Учитывая что все переменные здесь warning мб есть смысл переименовать в WarningPopUp

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/base_popup.py
> +        layout_type_body: Literal[
Аналогично, достаточно только Vertical

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/base_popup.py
> +        self._layout_main = QVBoxLayout()  # noqa
Зачем тогда был выбор типа лэйаута, лучше так оставить

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/buttons_popup/press_button_popup.py
> +class PressButtonPopUp(BaseButton):
думаю лучше просто PopUpButton

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/classic_popup.py
> +        header_control_panel.setFixedWidth(120)
ширину настраиваем из стилей

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/labels_popup/image_label_popup.py
> +        self.setStyleSheet(DEFAULT_IMAGE_DEFAULT_LABEL_POP_UP_STYLESHEET)
2 раза DEFAULT явно лишнее

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/yes_no_popup.py
> +        layout_type_body: Literal[
аналогично вертикал должен быть

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/yes_no_popup.py
> +        accept_button = PressButtonPopUp(parent=self, on_click=self.on_click, text="Accept")
лучше сделать on_click self.accept и self.reject и передавать в конструктор соотв функции

2024-02-24 08:58 UTC, artiebears13 commented on bin/gui/windows/pop_up/yes_no_popup.py
> +    def _on_click(self, func: Callable) -> Callable:
не уверен что лучшее решение

2024-02-24 09:15 UTC, AliRN9 commented on bin/gui/windows/pop_up/base_popup.py
> +        self._layout_main = QVBoxLayout()  # noqa
это main который включает в себя вертикально голову и тело 
А тело может быть вертикальным или горизонтальным

2024-02-24 09:23 UTC, AliRN9 commented on bin/gui/windows/pop_up/labels_popup/image_label_popup.py
> +        self.setStyleSheet(DEFAULT_IMAGE_DEFAULT_LABEL_POP_UP_STYLESHEET)
согласен

2024-02-25 10:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/alert_popup.py
> +        self, parent: QWidget, layout_type_body: Literal["HBox", "VBox"], title: str, alert_text: str, **kwargs
+ нейминг, лучше правильно порядок слов выбирать body_layout_type

2024-02-25 11:49 UTC, TeeMan508 requested changes

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/base_popup.py
> +            "VBox",
что с форматированием кода тут? Трудночитаемо как то

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/base_popup.py
> +        self._layout_main = QVBoxLayout()  # noqa
Нейминг: _main_layout. 

Определяются аттрибуты класса вне init

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/base_popup.py
> +        self._header_layout_popup = HeaderLayoutPopUp(parent=self, title=self.title)  # noqa
HeaderLayoutPopUp насчет нейминга обсудим

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/base_popup.py
> +    layout_types_body = {"HBox": HorizontalLayout, "VBox": VerticalLayout}
Почему только два типа? Любой может же быть в наполнении всплывающего окна

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/base_popup.py
> +        self._body_layout_popup = BasePopUp.layout_types_body.get(self.__layout_type_body)(self._parent)  # noqa
аналогично нейминг

get(), конечно, перестраховочный, поскольку ты typing'ом ограничил варианты. Но лучше привыкнуть ему в качестве второго аргумента давать дефолтное значение, которое он возвращает, если не найдет ключ(по дефолту это None)

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/base_popup.py
> +    def set_geometry(self, x: int, y: int, width: int, height: int):
такая реализация будет работать с нашими стилями, чтобы передать сюда геометрию из них?

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/buttons_popup/press_button_popup.py
> +class PressButtonPopUp(BaseButton):
согласен

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/labels_popup/label_popup.py
> +class LabelPopUp(BaseLabel):
Везде нейминг обсудим)

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/layouts_popup/header_layout_popup.py
> +        title_popup = LabelPopUp(self, text=self.title)
title_label

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/layouts_popup/header_layout_popup.py
> +    def _add_title(self) -> None:
_set_title тогда и в нем проверка на None

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/layouts_popup/header_layout_popup.py
> +    def __init__(self, parent: QWidget, title: str) -> None:
title: str or None по аналогии

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/yes_no_popup.py
> +        layout_type_body: Literal[
В целом аналогичные замечания как и в base

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/yes_no_popup.py
> +        accept_button = PressButtonPopUp(parent=self, on_click=self.on_click, text="Accept")
Согласен, реализацию двух кнопок здесь нужно обсудить

2024-02-25 11:49 UTC, TeeMan508 commented on bin/gui/windows/pop_up/yes_no_popup.py
> +        def wrapper():
согласен

2024-02-25 11:49 UTC, TeeMan508 commented on src/styles/components/windows/pop_up/label_popup/style.css
> +}
реализацию стилей лучше @artiebears13 проверь плиз

2024-02-25 11:57 UTC, AliRN9 commented on bin/gui/windows/pop_up/base_popup.py
> +            "VBox",
Это видимо прикоммиты подправили

2024-02-25 11:58 UTC, AliRN9 commented on bin/gui/windows/pop_up/base_popup.py
> +    layout_types_body = {"HBox": HorizontalLayout, "VBox": VerticalLayout}
Ну у нас вроде ток вроде две реализации: vertical и horizontal

2024-02-25 12:00 UTC, AliRN9 commented on bin/gui/windows/pop_up/base_popup.py
> +    def set_geometry(self, x: int, y: int, width: int, height: int):
Можно прост в стилях задать
Либо переопределить через этот метод

2024-02-29 20:37 UTC, AliRN9 commented on bin/gui/widgets/layouts/popup/header_layout.py
> -        if self.title is None:
Предвидя тут вопросы, сразу скажу
Нет обработки на None, потому что под капотом  Label  сам обрабатывает этот случай
и в этом случае создастся хедор, но без title

2024-03-01 14:50 UTC, closed without merging