Skrs 230
geoprotech/PowerEye_2 pull request #7
Opened 2024-03-07 10:43 UTC by artiebears13

2024-03-11 15:40 UTC, TeeMan508 requested changes

2024-03-11 15:40 UTC, TeeMan508 commented on bin/gui/widgets/layouts/left_menu.py
> +    def start_animation(self):
Все методы с анимацией private лучше сделать на всякий

2024-03-11 15:40 UTC, TeeMan508 commented on bin/gui/widgets/layouts/left_menu.py
> +        self.setGeometry(
Здесь лучше распаковку сделать, это и на будущее норм, тк геометрия в Stylesheet будет списком

2024-03-11 15:40 UTC, TeeMan508 commented on src/styles/components/widgets/layouts/left_menu_stub/style.css
>  }
Все четко, только мелкие правки
![image](https://github.com/geoprotech/PowerEye_2/assets/57092435/e28b85b1-5daa-4759-8a9e-4578c5792c92)

2024-03-13 08:01 UTC, artiebears13 commented on bin/gui/widgets/layouts/left_menu.py
> +    def start_animation(self):
не согласен, обсудим

2024-03-13 08:02 UTC, artiebears13 commented on bin/gui/widgets/layouts/left_menu.py
> +        self.setGeometry(
не пон

2024-03-19 06:06 UTC, merged